#!/usr/bin/bash

directories=("ffmpeg" "yt-dlp" "text" "mics")

# Loop over the array elements
for dir_name in "${directories[@]}"; do
	current_path="$(pwd)/bin/$dir_name"
	export PATH="$PATH:$current_path"
done
